[project]
name = "ds-persistencia-projeto02"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.17.2",
    "fastapi[standard]>=0.121.3",
    "python-dotenv>=1.2.1",
    "sqlmodel>=0.0.27",
]
